services:
  fastapi:
    build: .
    image: job-board:latest
    container_name: job_board_fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static_files:/code/static
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  
  
  postgres:
    image: postgres:16-alpine
    container_name: job_board_postgre
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]  
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s
      start_interval: 1s
    

  redis:
    image: redis:7-alpine
    container_name: job_board_redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
      start_interval: 1s

volumes:
  postgres_data:
  static_files:
    